/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{jsx,tsx}", "./components/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      fontFamily: {
        rubik: ["Rubik-Regular", "sans-serif"],
        "rubik-bold": ["Rubik-Bold", "sans-serif"],
        "rubik-extrabold": ["Rubik-ExtraBold", "sans-serif"],
        "rubik-medium": ["Rubik-Medium", "sans-serif"],
        "rubik-semibold": ["Rubik-SemiBold", "sans-serif"],
        "rubik-light": ["Rubik-Light", "sans-serif"],
      },
      colors: {
        coffeeTheme: {
          primary: "#8B593E",
          background: "#FFF8F3",
          text: "#4A3428",
          border: "#E5D3B7",
          white: "#FFFFFF",
          textLight: "#9A8478",
          expense: "#E74C3C",
          income: "#2ECC71",
          card: "#FFFFFF",
          shadow: "#000000",
        },
        forestTheme: {
          primary: "#2E7D32",
          background: "#E8F5E9",
          text: "#1B5E20",
          border: "#C8E6C9",
          white: "#FFFFFF",
          textLight: "#66BB6A",
          expense: "#C62828",
          income: "#388E3C",
          card: "#FFFFFF",
          shadow: "#000000",
        },
        purpleTheme: {
          primary: "#6A1B9A",
          background: "#F3E5F5",
          text: "#4A148C",
          border: "#D1C4E9",
          white: "#FFFFFF",
          textLight: "#BA68C8",
          expense: "#D32F2F",
          income: "#388E3C",
          card: "#FFFFFF",
          shadow: "#000000",
        },
        oceanTheme: {
          primary: "#0277BD",
          background: "#E1F5FE",
          text: "#01579B",
          border: "#B3E5FC",
          white: "#FFFFFF",
          textLight: "#4FC3F7",
          expense: "#EF5350",
          income: "#26A69A",
          card: "#FFFFFF",
          shadow: "#000000",
        },
      },
    },
  },
  plugins: [],
};
